name: Build main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security-checks:
    runs-on: ubuntu-20.04

    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Scaning code
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "table"
          template: "@/contrib/sarif.tpl"
          severity: "MEDIUM,HIGH,CRITICAL"

  qa:
    runs-on: ubuntu-20.04

    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Check format
        run: npm run format
      - name: Testing
        run: npm t
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      - name: Uploading coverage
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage/lcov.info
        env:
          CODACY_PROJECT_NAME: "gh-contribution-stats"
          CODACY_ORGANIZATION_PROVIDER: "gh"
          CODACY_USERNAME: "${{ github.repository_owner }}"