name: Pull request review

on:
  pull_request:
  workflow_dispatch:

jobs:
  detect-secrets:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Detecting secrets
        uses: reviewdog/action-detect-secrets@v0.13
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.github_token }}
          fail_on_error: true
          detect_secrets_flags: --exclude-files .git

  review-yaml:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Reviewing yaml files
        uses: reviewdog/action-yamllint@v1.8
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.github_token }}
          fail_on_error: true

  security-scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Scaning code
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "table"
          template: "@/contrib/sarif.tpl"
          severity: "MEDIUM,HIGH,CRITICAL"

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Check format
        run: npm run format

  pr-qa:
    runs-on: ubuntu-20.04
    needs:
      - lint
      - security-scan
      - review-yaml
      - detect-secrets
    steps:
      - name: Ready for merging
        run: echo "Ready to be merged"
